
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Puspita
 */
public class COBA extends javax.swing.JFrame {
String temp ="";
Double ti, bi, hi;
    /**
     * Creates new form COBA
     */
    public COBA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        berat = new javax.swing.JTextField();
        tinggi = new javax.swing.JTextField();
        pr = new javax.swing.JRadioButton();
        lk = new javax.swing.JRadioButton();
        jButtonHitung = new javax.swing.JButton();
        jButtonCoba = new javax.swing.JButton();
        jButtonKeluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ideal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hasil = new javax.swing.JTextField();
        saran = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 10, 140, 20);
        getContentPane().add(nama);
        nama.setBounds(150, 50, 130, 30);
        getContentPane().add(berat);
        berat.setBounds(160, 130, 70, 30);
        getContentPane().add(tinggi);
        tinggi.setBounds(160, 90, 70, 30);

        buttonGroup1.add(pr);
        pr.setText("Perempuan");
        pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prActionPerformed(evt);
            }
        });
        getContentPane().add(pr);
        pr.setBounds(160, 180, 110, 23);

        buttonGroup1.add(lk);
        lk.setText("Laki - laki");
        lk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lkActionPerformed(evt);
            }
        });
        getContentPane().add(lk);
        lk.setBounds(270, 180, 100, 23);

        jButtonHitung.setText("Hitung");
        jButtonHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHitungActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHitung);
        jButtonHitung.setBounds(30, 220, 70, 30);

        jButtonCoba.setText("Coba Lagi");
        jButtonCoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCobaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCoba);
        jButtonCoba.setBounds(153, 220, 90, 30);

        jButtonKeluar.setText("Keluar");
        jButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonKeluar);
        jButtonKeluar.setBounds(273, 220, 90, 30);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 50, 70, 20);

        jLabel3.setText("Tinggi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 90, 90, 20);

        jLabel4.setText("Berat Badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 130, 80, 20);

        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 180, 90, 20);

        ideal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idealActionPerformed(evt);
            }
        });
        getContentPane().add(ideal);
        ideal.setBounds(230, 280, 100, 30);

        jLabel6.setText("kg");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(340, 290, 30, 14);

        jLabel7.setText("Berat badan ideal anda adalah ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 280, 200, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 330, 200, 30);

        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        getContentPane().add(hasil);
        hasil.setBounds(39, 370, 340, 30);
        getContentPane().add(saran);
        saran.setBounds(39, 410, 340, 30);

        jLabel9.setText("cm");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(240, 100, 30, 14);

        jLabel10.setText("kg");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(240, 140, 40, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idealActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilActionPerformed

    private void jButtonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHitungActionPerformed
        if(nama.getText().equals("")||tinggi.getText().equals("")||berat.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Data harus diisikan semua");
        }
        else if (pr.isSelected()||lk.isSelected())
         {
                try
                {
                    Proses();
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Inputan ada yang belum diisi");
                }
         } else {
                JOptionPane.showMessageDialog(null, "Pilih salah satu jenis kelamin");
                }        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHitungActionPerformed

    private void jButtonCobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCobaActionPerformed
        nama.setText("");
        tinggi.setText("");
        berat.setText("");
        ideal.setText("");
        hasil.setText("");
        saran.setText("");
        buttonGroup1.clearSelection();
        
                // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCobaActionPerformed

    private void jButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKeluarActionPerformed
           System.exit(0);
           
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKeluarActionPerformed

    private void prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prActionPerformed
        pr.setSelected(false);       
        // TODO add your handling code here:
    }//GEN-LAST:event_prActionPerformed

    private void lkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lkActionPerformed
        lk.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_lkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(COBA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(COBA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(COBA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(COBA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new COBA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField berat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField hasil;
    private javax.swing.JTextField ideal;
    private javax.swing.JButton jButtonCoba;
    private javax.swing.JButton jButtonHitung;
    private javax.swing.JButton jButtonKeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton lk;
    private javax.swing.JTextField nama;
    private javax.swing.JRadioButton pr;
    private javax.swing.JTextField saran;
    private javax.swing.JTextField tinggi;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        ti = Double.parseDouble(tinggi.getText());
        bi = Double.parseDouble(berat.getText());
        
        if (lk.isSelected()) {
            hi = (ti - 100) * 1;
        } else if (pr.isSelected()){
            hi = (ti - 104) *1;
        }
        temp = Double.toString(hi.intValue());
        
        if(hi<bi){
            ideal.setText(temp);
            hasil.setText("Maaf " + nama.getText() + ", Sepertinya anda Overweight");
            saran.setText("Banyaklah berolahraga dan hindari makanan berkolesterol");
        } else if(hi>bi){
            ideal.setText(temp);
            hasil.setText("Maaf " + nama.getText() + ", Sepertinya anda Underweight");
            saran.setText("Banyaklah mengkonsumsi makanan yang berkarbohidrat");
        } else {
            ideal.setText(temp);
            hasil.setText(nama.getText() + "Berat badana anda sudah ideal");
            saran.setText("Tetaplah menjaga pola makan dan hidup sehat");
        } //To change body of generated methods, choose Tools | Templates.
    }
}
